on: [push, pull_request]
name: Lint
jobs:
  test:
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
